### ISSUE TITLE
the help option is not working

### ISSUE THREAD

**Issue by lkabuci** [mrshmllow/gh-cal#1]
![Screenshot_20220430_155053](https://user-images.githubusercontent.com/95357302/166112772-107bad72-1864-442b-bf76-d02d627bee9e.png)

**Comment by mrshmllow** [comment]
simply use -h *or* --help.

**Comment by lkabuci** [comment]
Well I think you should separate them 
It looks like a pipe to get the output

**Comment by mrshmllow** [comment]
a | is a standard *or*.
